### ISSUE TITLE
Crash with Burundi record on startup

### ISSUE THREAD

**Issue by loxs** [marinakr/libphonenumber_erlang#16]
The application crashes with this stack trace on startup:

```
  crasher:
    initial call: supervisor:libphonenumber_erlang_sup/1
    pid: <0.835.0>
    registered_name: []
    exception exit: {aborted,
                        {bad_type,
                            {countryphones,<<"257">>,
                                [{code_set,<<"BI">>,
                                     [{8,8}],
                                     <<"Burundi">>,
                                     <<"(?:29|31|6[189]|7[125-9])\\d{6}">>,
                                     undefined}]}}}
      in function  mnesia:abort/1 (mnesia.erl, line 351)
      in call from mnesia:do_dirty_write/3 (mnesia.erl, line 1704)
      in call from lists:foldl/3 (lists.erl, line 1263)
      in call from libphonenumber_erlang_sup:load_countryphonenumbers_rules/0 (libphonenumber_erlang/src/libphonenumber_erlang_sup.erl, line 27)
      in call from libphonenumber_erlang_sup:init/1 (libphonenumber_erlang/src/libphonenumber_erlang_sup.erl, line 14)
      in call from supervisor:init/1 (supervisor.erl, line 294)
      in call from gen_server:init_it/2 (gen_server.erl, line 365)
      in call from gen_server:init_it/6 (gen_server.erl, line 333)
```

**Comment by marinakr** [comment]
Can you show what was called before this crash? I'll check it

**Comment by loxs** [comment]
That's on application startup. I presume something like `application:start(libphonenumber_erlang)` was called by the startup scripts.
 
If you cannot reproduce it, I can create a small app that has `libphonenumber_erlang` as a dependency.

**Comment by marinakr** [comment]
Yes, it will be really helpful, because I can't reproduce it. Also, are you sure your mnesia is clear and has no outside records?

**Comment by loxs** [comment]
Ah, so then it might be if the app tries to start two times. I'll try to figure this out.

**Comment by marinakr** [comment]
File with actual metadata was updated, check new master

**Comment by loxs** [comment]
No, it still crashes.

And with a small app with just one dependency it doesn't crash. So it seems to be some problem with my setup, I'll try to debug it when I have time, but at this point I presume it's not a problem of `libphonenumber_erlang`

**Comment by marinakr** [comment]
it crashes after you cleared Mnesia dir?

**Comment by loxs** [comment]
Hmm, this fixed it. Does it mean that `libphonenumber_erlang` mnesia table is persistent? I previously used an older version of the library.

Why not just in memory table? It will be faster and it won't require clearing Mnesia when we upgrade libphonenumber_erlang. Probably you don't even need Mnesia, just ETS would do.

**Comment by marinakr** [comment]
Yes, nice idea. Persistent storage was used because there was no reason to parse xml on start every time. But I'll change code to avoid disc storage

**Comment by marinakr** [comment]
https://github.com/marinakr/libphonenumber_erlang/pull/18
