### ISSUE TITLE
US or RU numbers does not work, always returns false for valid numbers

### ISSUE THREAD

**Issue by etxemag75** [marinakr/libphonenumber_erlang#2]
When trying valid US or RU mobile numbers, it always returns false.

Examples:

phone_utils:mobile_phone_number_info(<<"+14088881406">>).
#{valid => false}

phone_utils:is_mobile_valid_phone(<<"+79021234567">>). 
false

**Comment by marinakr** [comment]
Thank you, I'll fix it as soon as possible

**Comment by marinakr** [comment]
https://github.com/marinakr/libphonenumber_erlang/commit/0a4a18ea5a1ec8fc0244e501ae1c3842087371c3
Fix it
Remove your old mnesia directory

**Comment by marinakr** [comment]
You should remove Mnesia directory  but not delete the table. Please exactly remove your mnesia directory and than check does the issue still reproduce. If you not sure where your mnesia dir, check start.sh file

**Comment by marinakr** [comment]
`(libphonenumber_erlang@localhost)10> phone_utils:mobile_phone_number_info(<<"+14088881406">>). 
#{country_metadata =>
      #{code => <<"1">>,id => <<"US">>,name => <<"United States">>},
  errors => [],phone => <<"+14088881406">>,valid => true}
(libphonenumber_erlang@localhost)11> 
(libphonenumber_erlang@localhost)11> phone_utils:mobile_phone_number_info(<<"+79021234567">>).
#{country_metadata =>
      #{code => <<"7">>,id => <<"RU">>,
        name => <<"Russian Federation">>},
  errors => [],phone => <<"+79021234567">>,valid => true}`
@etxemag75  Do still has issues?   If you do, try do remove all directory and git clone again. Meanwhile I ll add code to clear data on each start

**Comment by etxemag75** [comment]
Thx, seems to work now, you could close this ticket. :)

How do you test this library, do you have huge list of known phone numbers to test against?

**Comment by marinakr** [comment]
Check last issue about test. Any PR s are welcome, so feel free to impprove the lib
