### ISSUE TITLE
Make test cover

### ISSUE THREAD

**Issue by marinakr** [marinakr/libphonenumber_erlang#8]
Add test on all success and error cases

**Comment by etxemag75** [comment]
A good start is to extract out all 'exampleNumber' from PhoneNumberMetadata.xml and run them through this program (phone_utils:is_mobile_valid_phone/1 etc), at least 1104 valid phone numbers from all around the world are specified.

**Comment by marinakr** [comment]
https://github.com/marinakr/libphonenumber_erlang/pull/11
